export const EXPENSE_CATEGORIES = [
  {
    id: "DIRECT_MATERIALS",
    name: "Direct Materials & Parts (COGS)",
    ar: "المواد وقطع الغيار المباشرة",
    items: [
      ["Engine Spare Parts", "قطع غيار المحرك"],
      ["Gearbox & Transmission Parts", "قطع غيار ناقل الحركة"],
      ["Brake Parts", "قطع غيار الفرامل"],
      ["Suspension & Steering Parts", "قطع غيار التعليق والتوجيه"],
      ["Electrical Spare Parts", "قطع غيار كهربائية"],
      ["Battery Purchase", "شراء البطاريات"],
      ["Tyres & Tubes", "الإطارات والأنابيب الداخلية"],
      ["AC Spare Parts", "قطع غيار تكييف السيارات"],
      ["Body Repair Parts", "قطع غيار هيكل السيارة"],
      ["Paint & Painting Materials", "الدهانات ومواد الطلاء"],
      ["Engine Oil", "زيت المحرك"],
      ["Gear Oil & Transmission Fluid", "زيت ناقل الحركة"],
      ["Coolant & Radiator Fluid", "سائل تبريد المحرك"],
      ["Brake Fluid", "زيت الفرامل"],
      ["Filters", "الفلاتر"],
      ["Belts & Hoses", "السيور والخراطيم"],
      ["Bolts, Nuts & Screws", "البراغي والصواميل والمسامير"],
      ["Welding Materials for Jobs", "مواد اللحام لأعمال الصيانة"],
      ["Other Spare Parts", "قطع غيار أخرى"],
      ["Other Job Materials", "مواد أخرى لأعمال الصيانة"],
    ],
  },
  {
    id: "DIRECT_LABOR",
    name: "Direct Labor",
    ar: "العمالة المباشرة",
    items: [
      ["Mechanic Salary / Wages", "رواتب وأجور الميكانيكيين"],
      ["Electrician Salary / Wages", "رواتب وأجور الكهربائيين"],
      ["AC Technician Salary / Wages", "رواتب وأجور فنيي التكييف"],
      ["Painter Salary / Wages", "رواتب وأجور فنيي الدهان"],
      ["Denter / Body Technician Wages", "أجور فنيي السمكرة"],
      ["Welder Salary / Wages", "رواتب وأجور اللحامين"],
      ["Helper / Workshop Labor Wages", "أجور عمال ومساعدي الورشة"],
      ["Technician Overtime", "العمل الإضافي للفنيين"],
      ["Daily Labor Payment", "أجور العمالة اليومية"],
      ["Outside Mechanic Charges", "أجور ميكانيكي خارجي"],
      ["Outside Electrician Charges", "أجور كهربائي خارجي"],
      ["Outside Painting Charges", "تكاليف الدهان الخارجي"],
      ["Outside Machine Shop Charges", "تكاليف ورشة الخراطة الخارجية"],
      ["Other Outsourced Job Labor", "أجور عمالة خارجية أخرى"],
    ],
  },
  {
    id: "SHOP_OVERHEAD",
    name: "Shop Overhead & Utilities",
    ar: "المصاريف العامة للورشة والخدمات",
    items: [
      ["Workshop Rent", "إيجار الورشة"],
      ["Electricity Bill", "فاتورة الكهرباء"],
      ["Water Bill", "فاتورة المياه"],
      ["Internet Bill", "فاتورة الإنترنت"],
      ["Workshop Telephone Bill", "فاتورة هاتف الورشة"],
      ["Workshop Cleaning Materials", "مواد تنظيف الورشة"],
      ["Workshop Cleaning Service", "خدمات تنظيف الورشة"],
      ["Garbage Collection", "جمع النفايات"],
      ["Waste Oil Disposal", "التخلص من الزيوت المستعملة"],
      ["Pest Control", "مكافحة الحشرات"],
      ["Workshop Building Repair", "إصلاح مبنى الورشة"],
      ["Lighting & Electrical Repairs", "إصلاح الإنارة والكهرباء"],
      ["Plumbing Repairs", "إصلاحات السباكة"],
      ["Air Conditioner Maintenance", "صيانة أجهزة التكييف"],
      ["Fire Extinguisher Maintenance", "صيانة طفايات الحريق"],
      ["Workshop Security", "أمن وحراسة الورشة"],
      ["Workshop Drinking Water", "مياه الشرب للورشة"],
      ["Labor Food / Meals", "وجبات العمال"],
      ["Staff Tea & Coffee", "الشاي والقهوة للموظفين"],
      ["Staff Snacks & Refreshments", "الوجبات الخفيفة والمرطبات للموظفين"],
      ["Guest Tea & Coffee", "الشاي والقهوة للضيوف"],
      ["Guest Food / Meals", "وجبات الضيوف"],
      ["Guest Refreshments", "المرطبات للضيوف"],
      ["Customer Waiting Area Supplies", "مستلزمات منطقة انتظار العملاء"],
      ["Staff Accommodation Rent", "إيجار سكن الموظفين"],
      ["Staff Accommodation Utilities", "خدمات ومرافق سكن الموظفين"],
      ["Workshop First Aid Supplies", "مستلزمات الإسعافات الأولية"],
      ["Staff Uniforms", "الزي الرسمي للموظفين"],
      ["Staff Safety Equipment", "معدات السلامة للموظفين"],
      ["Other Workshop Overheads", "مصاريف عامة أخرى للورشة"],
    ],
  },
  {
    id: "TOOLS_MACHINERY",
    name: "Tools & Machinery Expenses",
    ar: "مصاريف الأدوات والمعدات",
    items: [
      ["Hand Tools", "الأدوات اليدوية"],
      ["Power Tools", "الأدوات الكهربائية"],
      ["Diagnostic Scanner Maintenance", "صيانة جهاز فحص السيارات"],
      ["Hydraulic Lift Maintenance", "صيانة الرافعات الهيدروليكية"],
      ["Air Compressor Maintenance", "صيانة ضاغط الهواء"],
      ["Welding Machine Maintenance", "صيانة ماكينة اللحام"],
      ["Workshop Machine Repairs", "إصلاح آلات الورشة"],
      ["Tool Repair", "إصلاح الأدوات"],
      ["Tool Calibration", "معايرة الأدوات"],
      ["Equipment Rental", "استئجار المعدات"],
      ["Drill Bits & Cutting Discs", "ريش المثقاب وأقراص القطع"],
      ["Grinding Wheels", "أقراص التجليخ"],
      ["Small Tool Replacement", "استبدال الأدوات الصغيرة"],
      ["Machinery Lubricants", "زيوت تشحيم الآلات"],
      ["Equipment Depreciation", "إهلاك المعدات"],
    ],
  },
  {
    id: "ADMIN_OPEX",
    name: "Operating & Administrative Expenses (OPEX)",
    ar: "المصاريف التشغيلية والإدارية",
    items: [
      ["Office Staff Salary", "رواتب موظفي المكتب"],
      ["Manager Salary", "راتب المدير"],
      ["Accountant Salary", "راتب المحاسب"],
      ["Receptionist Salary", "راتب موظف الاستقبال"],
      ["Office Stationery", "القرطاسية المكتبية"],
      ["Printing & Photocopying", "الطباعة والتصوير"],
      ["Printer Ink & Toner", "أحبار الطابعات"],
      ["Office Cleaning Supplies", "مستلزمات تنظيف المكتب"],
      ["Office Furniture Repair", "إصلاح الأثاث المكتبي"],
      ["Computer Repair", "إصلاح أجهزة الكمبيوتر"],
      ["Software Subscription", "اشتراكات البرامج"],
      ["Accounting Software", "برامج المحاسبة"],
      ["Business Mobile Recharge", "شحن جوالات العمل"],
      ["Business Internet / IT Services", "خدمات الإنترنت وتقنية المعلومات"],
      ["Business License Renewal", "تجديد رخصة النشاط"],
      ["Municipality Fees", "الرسوم البلدية"],
      ["Government Service Fees", "رسوم الخدمات الحكومية"],
      ["Commercial Registration Renewal", "تجديد السجل التجاري"],
      ["Business Insurance", "تأمين المنشأة"],
      ["Bank Charges", "الرسوم البنكية"],
      ["POS / Card Machine Fees", "رسوم أجهزة نقاط البيع"],
      ["Accounting & Legal Fees", "أتعاب المحاسبة والخدمات القانونية"],
      ["Advertising & Marketing", "الدعاية والتسويق"],
      ["Website & Domain Charges", "رسوم الموقع الإلكتروني والنطاق"],
      ["Business Travel", "مصاريف سفر العمل"],
      ["Business Fuel", "وقود مركبات العمل"],
      ["Business Vehicle Maintenance", "صيانة مركبات العمل"],
      ["Courier & Delivery Charges", "رسوم الشحن والتوصيل"],
      ["Staff Recruitment Fees", "رسوم استقدام وتوظيف الموظفين"],
      ["Staff Training", "تدريب الموظفين"],
      ["Work Permit / Iqama Renewal", "تجديد رخص العمل والإقامات"],
      ["Other Administrative Expenses", "مصاريف إدارية أخرى"],
    ],
  },
];

export const EXPENSE_SUBCATEGORIES = EXPENSE_CATEGORIES.flatMap(
  (category) =>
    category.items.map(([en, ar]) => ({
      en,
      ar,
      categoryId: category.id,
    })),
);

export function getExpenseLabel(value) {
  const item = EXPENSE_SUBCATEGORIES.find(
    (entry) => entry.en === value,
  );

  return item ? `${item.en} — ${item.ar}` : value;
}

export function getExpenseCategory(value) {
  const item = EXPENSE_SUBCATEGORIES.find(
    (entry) => entry.en === value,
  );

  return item
    ? EXPENSE_CATEGORIES.find(
        (category) => category.id === item.categoryId,
      )
    : null;
}
